INSERT INTO STATUS (ID, LOCATIONID, MONEY, SIZE)VALUES (1, 'Buenos Aires', 500, 'medium');
INSERT INTO STATUS (ID, LOCATIONID, MONEY, SIZE)VALUES (2, 'Rosario', 300, 'small');
INSERT INTO STATUS (ID, LOCATIONID, MONEY, SIZE)VALUES (3,'Bariloche', 800, 'Large');
